// src/ui/banner-art.ts
// AUTO-GENERATED by scripts/build-banner.ts from ~/Myceliate/myceliate_title.
// Re-run `pnpm tsx scripts/build-banner.ts` if the source art changes.

export type BannerRun = { text: string; fg: string };
export const BANNER_ROWS: readonly (readonly BannerRun[])[] = [
  [
    {
      text: '  ',
      fg: 'inherit',
    },
    {
      text: '██████████',
      fg: '#0000ff',
    },
    {
      text: '   ',
      fg: 'inherit',
    },
    {
      text: '██',
      fg: '#0000ff',
    },
    {
      text: '    ',
      fg: 'inherit',
    },
    {
      text: '██',
      fg: '#0000ff',
    },
    {
      text: ' ',
      fg: 'inherit',
    },
    {
      text: '█',
      fg: '#0000ff',
    },
    {
      text: '   ',
      fg: 'inherit',
    },
    {
      text: '██',
      fg: '#0000ff',
    },
    {
      text: '  ',
      fg: 'inherit',
    },
    {
      text: '██',
      fg: '#0000ff',
    },
    {
      text: '  ',
      fg: 'inherit',
    },
    {
      text: '███',
      fg: '#0000ff',
    },
    {
      text: ' ',
      fg: 'inherit',
    },
    {
      text: '██',
      fg: '#0000ff',
    },
    {
      text: '   ',
      fg: 'inherit',
    },
    {
      text: '███████',
      fg: '#0000ff',
    },
    {
      text: '  ',
      fg: 'inherit',
    },
    {
      text: '████',
      fg: '#0000ff',
    },
    {
      text: '    ',
      fg: 'inherit',
    },
    {
      text: '█████████',
      fg: '#0000ff',
    },
    {
      text: '     ',
      fg: 'inherit',
    },
    {
      text: '████',
      fg: '#0000ff',
    },
  ],
  [
    {
      text: '████',
      fg: '#0000ff',
    },
    {
      text: '█',
      fg: '#000000',
    },
    {
      text: '█',
      fg: '#eeeeee',
    },
    {
      text: '██',
      fg: '#0000ff',
    },
    {
      text: '█',
      fg: '#000000',
    },
    {
      text: '█',
      fg: '#eeeeee',
    },
    {
      text: '████',
      fg: '#0000ff',
    },
    {
      text: '  ',
      fg: 'inherit',
    },
    {
      text: '█',
      fg: '#0000ff',
    },
    {
      text: '█',
      fg: '#0000d7',
    },
    {
      text: '  ',
      fg: 'inherit',
    },
    {
      text: '█',
      fg: '#0000d7',
    },
    {
      text: '██',
      fg: '#0000ff',
    },
    {
      text: ' ',
      fg: 'inherit',
    },
    {
      text: '█',
      fg: '#0000d7',
    },
    {
      text: '█',
      fg: '#0000ff',
    },
    {
      text: ' ',
      fg: 'inherit',
    },
    {
      text: '█',
      fg: '#0000d7',
    },
    {
      text: '█',
      fg: '#0000ff',
    },
    {
      text: '  ',
      fg: 'inherit',
    },
    {
      text: '█',
      fg: '#0000d7',
    },
    {
      text: '█',
      fg: '#0000ff',
    },
    {
      text: '  ',
      fg: 'inherit',
    },
    {
      text: '█',
      fg: '#0000ff',
    },
    {
      text: '█',
      fg: '#0000d7',
    },
    {
      text: '   ',
      fg: 'inherit',
    },
    {
      text: '██',
      fg: '#0000ff',
    },
    {
      text: '  ',
      fg: 'inherit',
    },
    {
      text: '██',
      fg: '#0000ff',
    },
    {
      text: '  ',
      fg: 'inherit',
    },
    {
      text: '█',
      fg: '#0000d7',
    },
    {
      text: '█',
      fg: '#0000ff',
    },
    {
      text: '    ',
      fg: 'inherit',
    },
    {
      text: '█',
      fg: '#0000ff',
    },
    {
      text: '   ',
      fg: 'inherit',
    },
    {
      text: '██',
      fg: '#0000d7',
    },
    {
      text: '  ',
      fg: 'inherit',
    },
    {
      text: '█',
      fg: '#0000ff',
    },
    {
      text: '   ',
      fg: 'inherit',
    },
    {
      text: '██',
      fg: '#0000d7',
    },
    {
      text: '  ',
      fg: 'inherit',
    },
    {
      text: '█',
      fg: '#0000ff',
    },
    {
      text: '   ',
      fg: 'inherit',
    },
    {
      text: '█',
      fg: '#0000d7',
    },
    {
      text: '█',
      fg: '#0000ff',
    },
  ],
  [
    {
      text: '██████████████',
      fg: '#0000ff',
    },
    {
      text: '  ',
      fg: 'inherit',
    },
    {
      text: '██████',
      fg: '#0000d7',
    },
    {
      text: '█',
      fg: '#0000ff',
    },
    {
      text: '  ',
      fg: 'inherit',
    },
    {
      text: '███',
      fg: '#0000d7',
    },
    {
      text: '  ',
      fg: 'inherit',
    },
    {
      text: '██',
      fg: '#0000d7',
    },
    {
      text: '   ',
      fg: 'inherit',
    },
    {
      text: '█',
      fg: '#0000d7',
    },
    {
      text: '     ',
      fg: 'inherit',
    },
    {
      text: '█',
      fg: '#0000d7',
    },
    {
      text: '       ',
      fg: 'inherit',
    },
    {
      text: '██',
      fg: '#0000d7',
    },
    {
      text: '    ',
      fg: 'inherit',
    },
    {
      text: '█',
      fg: '#0000d7',
    },
    {
      text: '    ',
      fg: 'inherit',
    },
    {
      text: '█',
      fg: '#0000d7',
    },
    {
      text: '      ',
      fg: 'inherit',
    },
    {
      text: '█',
      fg: '#0000d7',
    },
    {
      text: '     ',
      fg: 'inherit',
    },
    {
      text: '██',
      fg: '#0000d7',
    },
  ],
  [
    {
      text: ' ',
      fg: 'inherit',
    },
    {
      text: '█',
      fg: '#0000ff',
    },
    {
      text: '█',
      fg: '#0000d7',
    },
    {
      text: '█',
      fg: '#000087',
    },
    {
      text: '█',
      fg: '#0000d7',
    },
    {
      text: '█',
      fg: '#000087',
    },
    {
      text: '██',
      fg: '#0000ff',
    },
    {
      text: '█',
      fg: '#000087',
    },
    {
      text: '█',
      fg: '#0000d7',
    },
    {
      text: '█',
      fg: '#000087',
    },
    {
      text: '█',
      fg: '#0000d7',
    },
    {
      text: '█',
      fg: '#0000ff',
    },
    {
      text: '  ',
      fg: 'inherit',
    },
    {
      text: '██',
      fg: '#0000d7',
    },
    {
      text: ' ',
      fg: 'inherit',
    },
    {
      text: '█',
      fg: '#0000d7',
    },
    {
      text: '█',
      fg: '#0000af',
    },
    {
      text: ' ',
      fg: 'inherit',
    },
    {
      text: '█',
      fg: '#0000d7',
    },
    {
      text: '    ',
      fg: 'inherit',
    },
    {
      text: '█',
      fg: '#0000d7',
    },
    {
      text: '  ',
      fg: 'inherit',
    },
    {
      text: '██',
      fg: '#0000d7',
    },
    {
      text: '    ',
      fg: 'inherit',
    },
    {
      text: '█',
      fg: '#0000d7',
    },
    {
      text: '     ',
      fg: 'inherit',
    },
    {
      text: '██',
      fg: '#0000d7',
    },
    {
      text: '       ',
      fg: 'inherit',
    },
    {
      text: '█',
      fg: '#0000af',
    },
    {
      text: '█',
      fg: '#0000d7',
    },
    {
      text: '    ',
      fg: 'inherit',
    },
    {
      text: '██',
      fg: '#0000d7',
    },
    {
      text: ' ',
      fg: 'inherit',
    },
    {
      text: '███',
      fg: '#0000af',
    },
    {
      text: '     ',
      fg: 'inherit',
    },
    {
      text: '██',
      fg: '#0000af',
    },
    {
      text: '   ',
      fg: 'inherit',
    },
    {
      text: '██',
      fg: '#0000d7',
    },
  ],
  [
    {
      text: '      ',
      fg: 'inherit',
    },
    {
      text: '█',
      fg: '#0000ff',
    },
    {
      text: '█',
      fg: '#0000d7',
    },
    {
      text: '      ',
      fg: 'inherit',
    },
    {
      text: '██',
      fg: '#0000af',
    },
    {
      text: '  ',
      fg: 'inherit',
    },
    {
      text: '█',
      fg: '#0000af',
    },
    {
      text: '  ',
      fg: 'inherit',
    },
    {
      text: '█',
      fg: '#0000af',
    },
    {
      text: '   ',
      fg: 'inherit',
    },
    {
      text: '█',
      fg: '#0000af',
    },
    {
      text: '█',
      fg: '#0000d7',
    },
    {
      text: ' ',
      fg: 'inherit',
    },
    {
      text: '██',
      fg: '#0000af',
    },
    {
      text: '     ',
      fg: 'inherit',
    },
    {
      text: '█',
      fg: '#0000af',
    },
    {
      text: '███',
      fg: '#0000d7',
    },
    {
      text: '   ',
      fg: 'inherit',
    },
    {
      text: '█',
      fg: '#0000af',
    },
    {
      text: '        ',
      fg: 'inherit',
    },
    {
      text: '██',
      fg: '#0000af',
    },
    {
      text: '    ',
      fg: 'inherit',
    },
    {
      text: '██',
      fg: '#0000af',
    },
    {
      text: '   ',
      fg: 'inherit',
    },
    {
      text: '█',
      fg: '#0000af',
    },
    {
      text: '     ',
      fg: 'inherit',
    },
    {
      text: '█',
      fg: '#0000af',
    },
    {
      text: '   ',
      fg: 'inherit',
    },
    {
      text: '████',
      fg: '#0000af',
    },
    {
      text: '█',
      fg: '#0000d7',
    },
  ],
  [
    {
      text: '      ',
      fg: 'inherit',
    },
    {
      text: '█',
      fg: '#000087',
    },
    {
      text: '█',
      fg: '#0000af',
    },
    {
      text: '     ',
      fg: 'inherit',
    },
    {
      text: '██',
      fg: '#0000af',
    },
    {
      text: '     ',
      fg: 'inherit',
    },
    {
      text: '██',
      fg: '#0000af',
    },
    {
      text: '  ',
      fg: 'inherit',
    },
    {
      text: '██',
      fg: '#0000af',
    },
    {
      text: '  ',
      fg: 'inherit',
    },
    {
      text: '█',
      fg: '#0000af',
    },
    {
      text: '      ',
      fg: 'inherit',
    },
    {
      text: '██',
      fg: '#0000af',
    },
    {
      text: '     ',
      fg: 'inherit',
    },
    {
      text: '█',
      fg: '#0000af',
    },
    {
      text: '         ',
      fg: 'inherit',
    },
    {
      text: '█',
      fg: '#0000af',
    },
    {
      text: '     ',
      fg: 'inherit',
    },
    {
      text: '█',
      fg: '#0000af',
    },
    {
      text: '   ',
      fg: 'inherit',
    },
    {
      text: '█',
      fg: '#0000af',
    },
    {
      text: '█',
      fg: '#000087',
    },
    {
      text: '    ',
      fg: 'inherit',
    },
    {
      text: '█',
      fg: '#000087',
    },
    {
      text: '   ',
      fg: 'inherit',
    },
    {
      text: '█',
      fg: '#000087',
    },
  ],
  [
    {
      text: '      ',
      fg: 'inherit',
    },
    {
      text: '█',
      fg: '#00005f',
    },
    {
      text: '█',
      fg: '#000087',
    },
    {
      text: '   ',
      fg: 'inherit',
    },
    {
      text: '█',
      fg: '#000087',
    },
    {
      text: '█',
      fg: '#0000af',
    },
    {
      text: '       ',
      fg: 'inherit',
    },
    {
      text: '█',
      fg: '#000087',
    },
    {
      text: '█',
      fg: '#00005f',
    },
    {
      text: '  ',
      fg: 'inherit',
    },
    {
      text: '█',
      fg: '#000087',
    },
    {
      text: '   ',
      fg: 'inherit',
    },
    {
      text: '█',
      fg: '#000087',
    },
    {
      text: '       ',
      fg: 'inherit',
    },
    {
      text: '█',
      fg: '#00005f',
    },
    {
      text: '█',
      fg: '#000087',
    },
    {
      text: '    ',
      fg: 'inherit',
    },
    {
      text: '█',
      fg: '#000087',
    },
    {
      text: '         ',
      fg: 'inherit',
    },
    {
      text: '██',
      fg: '#000087',
    },
    {
      text: '    ',
      fg: 'inherit',
    },
    {
      text: '█',
      fg: '#000087',
    },
    {
      text: '    ',
      fg: 'inherit',
    },
    {
      text: '█',
      fg: '#00005f',
    },
    {
      text: '    ',
      fg: 'inherit',
    },
    {
      text: '██',
      fg: '#000087',
    },
    {
      text: '  ',
      fg: 'inherit',
    },
    {
      text: '█',
      fg: '#00005f',
    },
    {
      text: '█',
      fg: '#000087',
    },
  ],
  [
    {
      text: '      ',
      fg: 'inherit',
    },
    {
      text: '██',
      fg: '#00005f',
    },
    {
      text: '  ',
      fg: 'inherit',
    },
    {
      text: '██',
      fg: '#00005f',
    },
    {
      text: '       ',
      fg: 'inherit',
    },
    {
      text: '██',
      fg: '#00005f',
    },
    {
      text: '   ',
      fg: 'inherit',
    },
    {
      text: '█',
      fg: '#00005f',
    },
    {
      text: '   ',
      fg: 'inherit',
    },
    {
      text: '██',
      fg: '#00005f',
    },
    {
      text: '   ',
      fg: 'inherit',
    },
    {
      text: '██',
      fg: '#00005f',
    },
    {
      text: '  ',
      fg: 'inherit',
    },
    {
      text: '█',
      fg: '#00005f',
    },
    {
      text: '    ',
      fg: 'inherit',
    },
    {
      text: '██',
      fg: '#00005f',
    },
    {
      text: ' ',
      fg: 'inherit',
    },
    {
      text: '██',
      fg: '#00005f',
    },
    {
      text: '█',
      fg: '#000087',
    },
    {
      text: '   ',
      fg: 'inherit',
    },
    {
      text: '█',
      fg: '#00005f',
    },
    {
      text: '█',
      fg: '#000087',
    },
    {
      text: '███',
      fg: '#00005f',
    },
    {
      text: '  ',
      fg: 'inherit',
    },
    {
      text: '██',
      fg: '#00005f',
    },
    {
      text: '   ',
      fg: 'inherit',
    },
    {
      text: '█',
      fg: '#00005f',
    },
    {
      text: '     ',
      fg: 'inherit',
    },
    {
      text: '█',
      fg: '#00005f',
    },
    {
      text: '   ',
      fg: 'inherit',
    },
    {
      text: '██',
      fg: '#00005f',
    },
    {
      text: '█',
      fg: '#000087',
    },
  ],
  [
    {
      text: '      ',
      fg: 'inherit',
    },
    {
      text: '██',
      fg: '#00005f',
    },
    {
      text: '  ',
      fg: 'inherit',
    },
    {
      text: '██',
      fg: '#00005f',
    },
    {
      text: '       ',
      fg: 'inherit',
    },
    {
      text: '██',
      fg: '#00005f',
    },
    {
      text: '  ',
      fg: 'inherit',
    },
    {
      text: '██',
      fg: '#00005f',
    },
    {
      text: '    ',
      fg: 'inherit',
    },
    {
      text: '█████',
      fg: '#00005f',
    },
    {
      text: '   ',
      fg: 'inherit',
    },
    {
      text: '████',
      fg: '#00005f',
    },
    {
      text: '  ',
      fg: 'inherit',
    },
    {
      text: '██',
      fg: '#00005f',
    },
    {
      text: '  ',
      fg: 'inherit',
    },
    {
      text: '██',
      fg: '#00005f',
    },
    {
      text: ' ',
      fg: 'inherit',
    },
    {
      text: '██',
      fg: '#00005f',
    },
    {
      text: '   ',
      fg: 'inherit',
    },
    {
      text: '██',
      fg: '#00005f',
    },
    {
      text: '  ',
      fg: 'inherit',
    },
    {
      text: '█',
      fg: '#00005f',
    },
    {
      text: '   ',
      fg: 'inherit',
    },
    {
      text: '█',
      fg: '#00005f',
    },
    {
      text: '     ',
      fg: 'inherit',
    },
    {
      text: '█',
      fg: '#00005f',
    },
    {
      text: '      ',
      fg: 'inherit',
    },
    {
      text: '████',
      fg: '#00005f',
    },
  ],
] as const;
