// scripts/build-banner.ts
// One-shot generator: parse the durdraw file at ~/Myceliate/myceliate_title
// and emit `src/ui/banner-art.ts` containing the trimmed art as colour-run
// rows that Ink can render directly. Run on demand when the source art changes.
//
// Usage: pnpm tsx scripts/build-banner.ts
import { readFileSync, writeFileSync } from 'node:fs';
import { homedir } from 'node:os';
import { join } from 'node:path';
import { gunzipSync } from 'node:zlib';

// xterm-256 → hex, only the entries we need (16-21 blue ramp + 255 + 7 silver bg).
const PALETTE: Record<number, string> = {
  7: '#c0c0c0',
  16: '#000000',
  17: '#00005f',
  18: '#000087',
  19: '#0000af',
  20: '#0000d7',
  21: '#0000ff',
  255: '#eeeeee',
};

type DurFrame = {
  frameNumber: number;
  delay: number;
  contents: string[];
  colorMap: Array<Array<[number, number]>>; // [col][row] = [fg, bg]
};

type DurMovie = { DurMovie: { sizeX: number; sizeY: number; frames: DurFrame[] } };

const sourcePath = process.argv[2] ?? join(homedir(), 'Myceliate', 'myceliate_title');
const raw = readFileSync(sourcePath);
const json = gunzipSync(raw).toString('utf8');
const movie = JSON.parse(json) as DurMovie;
const frame = movie.DurMovie.frames[0];
if (!frame) throw new Error('no frame in movie');
const { contents, colorMap } = frame;
const sizeX = movie.DurMovie.sizeX;

// Identify the actual art area: rows that contain any non-space character.
const nonBlankRows: number[] = [];
for (let row = 0; row < contents.length; row += 1) {
  const r = contents[row] ?? '';
  if (r.replace(/\s/g, '').length > 0) nonBlankRows.push(row);
}
const firstRow = nonBlankRows[0];
const lastRow = nonBlankRows[nonBlankRows.length - 1];
if (firstRow === undefined || lastRow === undefined) throw new Error('frame is empty');

// Build colour-run rows. Each row is an array of {text, fg} runs; consecutive
// cells with the same fg get merged into a single run to keep the React tree small.
type Run = { text: string; fg: string };
const rows: Run[][] = [];
for (let row = firstRow; row <= lastRow; row += 1) {
  const rowChars = (contents[row] ?? '').padEnd(sizeX, ' ');
  const runs: Run[] = [];
  let current: Run | null = null;
  for (let col = 0; col < sizeX; col += 1) {
    const ch = rowChars[col] ?? ' ';
    const cell = colorMap[col]?.[row] ?? [255, 0];
    const [fgIdx] = cell;
    // Spaces don't carry colour visibly; collapse to a neutral fg so they don't
    // split runs unnecessarily.
    const fg = ch === ' ' ? 'inherit' : (PALETTE[fgIdx] ?? '#ffffff');
    if (current && current.fg === fg) {
      current.text += ch;
    } else {
      if (current) runs.push(current);
      current = { text: ch, fg };
    }
  }
  if (current) runs.push(current);
  // Trim trailing all-space runs from each row (purely cosmetic).
  while (
    runs.length > 0 &&
    runs[runs.length - 1]?.fg === 'inherit' &&
    runs[runs.length - 1]?.text.trim() === ''
  ) {
    runs.pop();
  }
  rows.push(runs);
}

const out = `// src/ui/banner-art.ts
// AUTO-GENERATED by scripts/build-banner.ts from ~/Myceliate/myceliate_title.
// Re-run \`pnpm tsx scripts/build-banner.ts\` if the source art changes.

export type BannerRun = { text: string; fg: string };
export const BANNER_ROWS: readonly (readonly BannerRun[])[] = ${JSON.stringify(rows, null, 2)} as const;
`;

const outPath = join(process.cwd(), 'src/ui/banner-art.ts');
writeFileSync(outPath, out, 'utf8');
console.log(
  `wrote ${outPath} — ${rows.length} rows, ${rows.reduce((n, r) => n + r.length, 0)} colour runs`,
);
